--Types of Relationship
-- One  to One
-- One to Many
-- Many to Many

create database store_db;

--
CREATE TABLE customers
(
    cust_id   SERIAL PRIMARY KEY,
    cust_name VARCHAR(100) NOT NULL
);

CREATE TABLE orders (
    ord_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    price NUMERIC NOT NULL,
    cust_id INT NOT NULL REFERENCES customers(cust_id)
);